// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Bill is the predicate function for bill builders.
type Bill func(*sql.Selector)

// Billingstatus is the predicate function for billingstatus builders.
type Billingstatus func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Repairinvoice is the predicate function for repairinvoice builders.
type Repairinvoice func(*sql.Selector)
