// Code generated by entc, DO NOT EDIT.

package billingstatus

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/prakitsrakaew/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Billingstatusname applies equality check predicate on the "billingstatusname" field. It's identical to BillingstatusnameEQ.
func Billingstatusname(v string) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBillingstatusname), v))
	})
}

// BillingstatusnameEQ applies the EQ predicate on the "billingstatusname" field.
func BillingstatusnameEQ(v string) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBillingstatusname), v))
	})
}

// BillingstatusnameNEQ applies the NEQ predicate on the "billingstatusname" field.
func BillingstatusnameNEQ(v string) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldBillingstatusname), v))
	})
}

// BillingstatusnameIn applies the In predicate on the "billingstatusname" field.
func BillingstatusnameIn(vs ...string) predicate.Billingstatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Billingstatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldBillingstatusname), v...))
	})
}

// BillingstatusnameNotIn applies the NotIn predicate on the "billingstatusname" field.
func BillingstatusnameNotIn(vs ...string) predicate.Billingstatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Billingstatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldBillingstatusname), v...))
	})
}

// BillingstatusnameGT applies the GT predicate on the "billingstatusname" field.
func BillingstatusnameGT(v string) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldBillingstatusname), v))
	})
}

// BillingstatusnameGTE applies the GTE predicate on the "billingstatusname" field.
func BillingstatusnameGTE(v string) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldBillingstatusname), v))
	})
}

// BillingstatusnameLT applies the LT predicate on the "billingstatusname" field.
func BillingstatusnameLT(v string) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldBillingstatusname), v))
	})
}

// BillingstatusnameLTE applies the LTE predicate on the "billingstatusname" field.
func BillingstatusnameLTE(v string) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldBillingstatusname), v))
	})
}

// BillingstatusnameContains applies the Contains predicate on the "billingstatusname" field.
func BillingstatusnameContains(v string) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldBillingstatusname), v))
	})
}

// BillingstatusnameHasPrefix applies the HasPrefix predicate on the "billingstatusname" field.
func BillingstatusnameHasPrefix(v string) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldBillingstatusname), v))
	})
}

// BillingstatusnameHasSuffix applies the HasSuffix predicate on the "billingstatusname" field.
func BillingstatusnameHasSuffix(v string) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldBillingstatusname), v))
	})
}

// BillingstatusnameEqualFold applies the EqualFold predicate on the "billingstatusname" field.
func BillingstatusnameEqualFold(v string) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldBillingstatusname), v))
	})
}

// BillingstatusnameContainsFold applies the ContainsFold predicate on the "billingstatusname" field.
func BillingstatusnameContainsFold(v string) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldBillingstatusname), v))
	})
}

// HasBillingstatuss applies the HasEdge predicate on the "billingstatuss" edge.
func HasBillingstatuss() predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(BillingstatussTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BillingstatussTable, BillingstatussColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBillingstatussWith applies the HasEdge predicate on the "billingstatuss" edge with a given conditions (other predicates).
func HasBillingstatussWith(preds ...predicate.Bill) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(BillingstatussInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BillingstatussTable, BillingstatussColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Billingstatus) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Billingstatus) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Billingstatus) predicate.Billingstatus {
	return predicate.Billingstatus(func(s *sql.Selector) {
		p(s.Not())
	})
}
