// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/prakitsrakaew/app/ent/bill"
	"github.com/prakitsrakaew/app/ent/billingstatus"
)

// BillingstatusCreate is the builder for creating a Billingstatus entity.
type BillingstatusCreate struct {
	config
	mutation *BillingstatusMutation
	hooks    []Hook
}

// SetBillingstatusname sets the billingstatusname field.
func (bc *BillingstatusCreate) SetBillingstatusname(s string) *BillingstatusCreate {
	bc.mutation.SetBillingstatusname(s)
	return bc
}

// AddBillingstatusIDs adds the billingstatuss edge to Bill by ids.
func (bc *BillingstatusCreate) AddBillingstatusIDs(ids ...int) *BillingstatusCreate {
	bc.mutation.AddBillingstatusIDs(ids...)
	return bc
}

// AddBillingstatuss adds the billingstatuss edges to Bill.
func (bc *BillingstatusCreate) AddBillingstatuss(b ...*Bill) *BillingstatusCreate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return bc.AddBillingstatusIDs(ids...)
}

// Mutation returns the BillingstatusMutation object of the builder.
func (bc *BillingstatusCreate) Mutation() *BillingstatusMutation {
	return bc.mutation
}

// Save creates the Billingstatus in the database.
func (bc *BillingstatusCreate) Save(ctx context.Context) (*Billingstatus, error) {
	if _, ok := bc.mutation.Billingstatusname(); !ok {
		return nil, &ValidationError{Name: "billingstatusname", err: errors.New("ent: missing required field \"billingstatusname\"")}
	}
	var (
		err  error
		node *Billingstatus
	)
	if len(bc.hooks) == 0 {
		node, err = bc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BillingstatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bc.mutation = mutation
			node, err = bc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(bc.hooks) - 1; i >= 0; i-- {
			mut = bc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BillingstatusCreate) SaveX(ctx context.Context) *Billingstatus {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bc *BillingstatusCreate) sqlSave(ctx context.Context) (*Billingstatus, error) {
	b, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	b.ID = int(id)
	return b, nil
}

func (bc *BillingstatusCreate) createSpec() (*Billingstatus, *sqlgraph.CreateSpec) {
	var (
		b     = &Billingstatus{config: bc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: billingstatus.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: billingstatus.FieldID,
			},
		}
	)
	if value, ok := bc.mutation.Billingstatusname(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: billingstatus.FieldBillingstatusname,
		})
		b.Billingstatusname = value
	}
	if nodes := bc.mutation.BillingstatussIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingstatus.BillingstatussTable,
			Columns: []string{billingstatus.BillingstatussColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bill.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return b, _spec
}
