// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/prakitsrakaew/app/ent/billingstatus"
)

// Billingstatus is the model entity for the Billingstatus schema.
type Billingstatus struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Billingstatusname holds the value of the "billingstatusname" field.
	Billingstatusname string `json:"billingstatusname,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BillingstatusQuery when eager-loading is set.
	Edges BillingstatusEdges `json:"edges"`
}

// BillingstatusEdges holds the relations/edges for other nodes in the graph.
type BillingstatusEdges struct {
	// Billingstatuss holds the value of the billingstatuss edge.
	Billingstatuss []*Bill
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// BillingstatussOrErr returns the Billingstatuss value or an error if the edge
// was not loaded in eager-loading.
func (e BillingstatusEdges) BillingstatussOrErr() ([]*Bill, error) {
	if e.loadedTypes[0] {
		return e.Billingstatuss, nil
	}
	return nil, &NotLoadedError{edge: "billingstatuss"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Billingstatus) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // billingstatusname
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Billingstatus fields.
func (b *Billingstatus) assignValues(values ...interface{}) error {
	if m, n := len(values), len(billingstatus.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	b.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field billingstatusname", values[0])
	} else if value.Valid {
		b.Billingstatusname = value.String
	}
	return nil
}

// QueryBillingstatuss queries the billingstatuss edge of the Billingstatus.
func (b *Billingstatus) QueryBillingstatuss() *BillQuery {
	return (&BillingstatusClient{config: b.config}).QueryBillingstatuss(b)
}

// Update returns a builder for updating this Billingstatus.
// Note that, you need to call Billingstatus.Unwrap() before calling this method, if this Billingstatus
// was returned from a transaction, and the transaction was committed or rolled back.
func (b *Billingstatus) Update() *BillingstatusUpdateOne {
	return (&BillingstatusClient{config: b.config}).UpdateOne(b)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (b *Billingstatus) Unwrap() *Billingstatus {
	tx, ok := b.config.driver.(*txDriver)
	if !ok {
		panic("ent: Billingstatus is not a transactional entity")
	}
	b.config.driver = tx.drv
	return b
}

// String implements the fmt.Stringer.
func (b *Billingstatus) String() string {
	var builder strings.Builder
	builder.WriteString("Billingstatus(")
	builder.WriteString(fmt.Sprintf("id=%v", b.ID))
	builder.WriteString(", billingstatusname=")
	builder.WriteString(b.Billingstatusname)
	builder.WriteByte(')')
	return builder.String()
}

// Billingstatuses is a parsable slice of Billingstatus.
type Billingstatuses []*Billingstatus

func (b Billingstatuses) config(cfg config) {
	for _i := range b {
		b[_i].config = cfg
	}
}
