// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// BillsColumns holds the columns for the "bills" table.
	BillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "price", Type: field.TypeInt, Unique: true},
		{Name: "time", Type: field.TypeInt, Unique: true},
		{Name: "billingstatus_id", Type: field.TypeInt, Nullable: true},
		{Name: "employee_id", Type: field.TypeInt, Nullable: true},
		{Name: "reparinvoice_id", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// BillsTable holds the schema information for the "bills" table.
	BillsTable = &schema.Table{
		Name:       "bills",
		Columns:    BillsColumns,
		PrimaryKey: []*schema.Column{BillsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "bills_billingstatuses_billingstatuss",
				Columns: []*schema.Column{BillsColumns[3]},

				RefColumns: []*schema.Column{BillingstatusesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "bills_employees_employees",
				Columns: []*schema.Column{BillsColumns[4]},

				RefColumns: []*schema.Column{EmployeesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "bills_repairinvoices_repairinvoices",
				Columns: []*schema.Column{BillsColumns[5]},

				RefColumns: []*schema.Column{RepairinvoicesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// BillingstatusesColumns holds the columns for the "billingstatuses" table.
	BillingstatusesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "billingstatusname", Type: field.TypeString, Unique: true},
	}
	// BillingstatusesTable holds the schema information for the "billingstatuses" table.
	BillingstatusesTable = &schema.Table{
		Name:        "billingstatuses",
		Columns:     BillingstatusesColumns,
		PrimaryKey:  []*schema.Column{BillingstatusesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// EmployeesColumns holds the columns for the "employees" table.
	EmployeesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "employeename", Type: field.TypeString, Unique: true},
		{Name: "employeeemail", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
	}
	// EmployeesTable holds the schema information for the "employees" table.
	EmployeesTable = &schema.Table{
		Name:        "employees",
		Columns:     EmployeesColumns,
		PrimaryKey:  []*schema.Column{EmployeesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// RepairinvoicesColumns holds the columns for the "repairinvoices" table.
	RepairinvoicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "symptomid", Type: field.TypeInt},
		{Name: "deviceid", Type: field.TypeInt},
		{Name: "userid", Type: field.TypeInt},
		{Name: "statusrepairid", Type: field.TypeInt},
	}
	// RepairinvoicesTable holds the schema information for the "repairinvoices" table.
	RepairinvoicesTable = &schema.Table{
		Name:        "repairinvoices",
		Columns:     RepairinvoicesColumns,
		PrimaryKey:  []*schema.Column{RepairinvoicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BillsTable,
		BillingstatusesTable,
		EmployeesTable,
		RepairinvoicesTable,
	}
)

func init() {
	BillsTable.ForeignKeys[0].RefTable = BillingstatusesTable
	BillsTable.ForeignKeys[1].RefTable = EmployeesTable
	BillsTable.ForeignKeys[2].RefTable = RepairinvoicesTable
}
