/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBill,
    EntBillFromJSON,
    EntBillFromJSONTyped,
    EntBillToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBillingstatusEdges
 */
export interface EntBillingstatusEdges {
    /**
     * Billingstatuss holds the value of the billingstatuss edge.
     * @type {Array<EntBill>}
     * @memberof EntBillingstatusEdges
     */
    billingstatuss?: Array<EntBill>;
}

export function EntBillingstatusEdgesFromJSON(json: any): EntBillingstatusEdges {
    return EntBillingstatusEdgesFromJSONTyped(json, false);
}

export function EntBillingstatusEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBillingstatusEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'billingstatuss': !exists(json, 'billingstatuss') ? undefined : ((json['billingstatuss'] as Array<any>).map(EntBillFromJSON)),
    };
}

export function EntBillingstatusEdgesToJSON(value?: EntBillingstatusEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'billingstatuss': value.billingstatuss === undefined ? undefined : ((value.billingstatuss as Array<any>).map(EntBillToJSON)),
    };
}


