// Code generated by entc, DO NOT EDIT.

package bill

const (
	// Label holds the string label denoting the bill type in the database.
	Label = "bill"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldTime holds the string denoting the time field in the database.
	FieldTime = "time"

	// EdgeRepairinvoice holds the string denoting the repairinvoice edge name in mutations.
	EdgeRepairinvoice = "Repairinvoice"
	// EdgeEmployee holds the string denoting the employee edge name in mutations.
	EdgeEmployee = "Employee"
	// EdgeBillingstatus holds the string denoting the billingstatus edge name in mutations.
	EdgeBillingstatus = "Billingstatus"

	// Table holds the table name of the bill in the database.
	Table = "bills"
	// RepairinvoiceTable is the table the holds the Repairinvoice relation/edge.
	RepairinvoiceTable = "bills"
	// RepairinvoiceInverseTable is the table name for the Repairinvoice entity.
	// It exists in this package in order to avoid circular dependency with the "repairinvoice" package.
	RepairinvoiceInverseTable = "repairinvoices"
	// RepairinvoiceColumn is the table column denoting the Repairinvoice relation/edge.
	RepairinvoiceColumn = "reparinvoice_id"
	// EmployeeTable is the table the holds the Employee relation/edge.
	EmployeeTable = "bills"
	// EmployeeInverseTable is the table name for the Employee entity.
	// It exists in this package in order to avoid circular dependency with the "employee" package.
	EmployeeInverseTable = "employees"
	// EmployeeColumn is the table column denoting the Employee relation/edge.
	EmployeeColumn = "employee_id"
	// BillingstatusTable is the table the holds the Billingstatus relation/edge.
	BillingstatusTable = "bills"
	// BillingstatusInverseTable is the table name for the Billingstatus entity.
	// It exists in this package in order to avoid circular dependency with the "billingstatus" package.
	BillingstatusInverseTable = "billingstatuses"
	// BillingstatusColumn is the table column denoting the Billingstatus relation/edge.
	BillingstatusColumn = "billingstatus_id"
)

// Columns holds all SQL columns for bill fields.
var Columns = []string{
	FieldID,
	FieldPrice,
	FieldTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Bill type.
var ForeignKeys = []string{
	"billingstatus_id",
	"employee_id",
	"reparinvoice_id",
}
